[2024-06-16T18:23:20.574+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: s3_to_ml_to_postgres.setup_create_table manual__2024-06-16T18:21:38.105505+00:00 [queued]>
[2024-06-16T18:23:20.577+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: s3_to_ml_to_postgres.setup_create_table manual__2024-06-16T18:21:38.105505+00:00 [queued]>
[2024-06-16T18:23:20.577+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-06-16T18:23:20.582+0000] {taskinstance.py:2191} INFO - Executing <Task(RedshiftDataOperator): setup_create_table> on 2024-06-16 18:21:38.105505+00:00
[2024-06-16T18:23:20.585+0000] {standard_task_runner.py:60} INFO - Started process 30860 to run task
[2024-06-16T18:23:20.587+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 's3_to_ml_to_postgres', 'setup_create_table', 'manual__2024-06-16T18:21:38.105505+00:00', '--job-id', '133', '--raw', '--subdir', 'DAGS_FOLDER/ml_dataset_preparation.py', '--cfg-path', '/tmp/tmpj_u09444']
[2024-06-16T18:23:20.588+0000] {standard_task_runner.py:88} INFO - Job 133: Subtask setup_create_table
[2024-06-16T18:23:20.608+0000] {task_command.py:423} INFO - Running <TaskInstance: s3_to_ml_to_postgres.setup_create_table manual__2024-06-16T18:21:38.105505+00:00 [running]> on host 22dc78ccc862
[2024-06-16T18:23:20.639+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='s3_to_ml_to_postgres' AIRFLOW_CTX_TASK_ID='setup_create_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-16T18:21:38.105505+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-16T18:21:38.105505+00:00'
[2024-06-16T18:23:20.640+0000] {redshift_data.py:122} INFO - Executing statement: 
DROP TABLE IF EXISTS transformed_data;
CREATE TABLE transformed_data(
                stationcode bigint,
                name varchar(255),
                is_installed boolean,
                capacity int,
                numdocksavailable int,
                numbikesavailable int,
                mechanical int,
                ebike int,
                is_renting boolean,
                is_returning boolean,
                nom_arrondissement_communes varchar(255),
                code_insee_commune varchar(255),
                longitude double precision, 
                latitude double precision, 
                date timestamp, 
                year int, 
                month int, 
                day int, 
                time time
                );
    
[2024-06-16T18:23:20.644+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2024-06-16T18:23:20.644+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2024-06-16T18:23:21.933+0000] {redshift_data.py:113} INFO - Polling statement 89441591-f85c-49c0-81e2-7f3779506201
[2024-06-16T18:23:22.044+0000] {redshift_data.py:129} INFO - Query PICKED
[2024-06-16T18:23:32.047+0000] {redshift_data.py:113} INFO - Polling statement 89441591-f85c-49c0-81e2-7f3779506201
[2024-06-16T18:23:32.229+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/operators/redshift_data.py", line 124, in execute
    self.statement_id = self.hook.execute_query(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 107, in execute_query
    self.wait_for_results(statement_id, poll_interval=poll_interval)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 124, in wait_for_results
    raise ValueError(
ValueError: Statement '89441591-f85c-49c0-81e2-7f3779506201' terminated with status FAILED. Response details: {'CreatedAt': datetime.datetime(2024, 6, 16, 18, 23, 21, 605000, tzinfo=tzlocal()),
 'Database': 'dev',
 'DbUser': 'IAM:kevin_project',
 'Duration': -1,
 'Error': 'ERROR: permission denied for relation transformed_data',
 'HasResultSet': False,
 'Id': '89441591-f85c-49c0-81e2-7f3779506201',
 'QueryString': '\n'
                'DROP TABLE IF EXISTS transformed_data;\n'
                'CREATE TABLE transformed_data(\n'
                '                stationcode bigint,\n'
                '                name varchar(255),\n'
                '                is_installed boolean,\n'
                '                capacity int,\n'
                '                numdocksavailable int,\n'
                '                numbikesavailable int,\n'
                '                mechanical int,\n'
                '                ebike int,\n'
                '                is_renting boolean,\n'
                '                is_returning boolean,\n'
                '                nom_arrondissement_communes varchar(255),\n'
                '                code_insee_commune varchar(255),\n'
                '                longitude double precision, \n'
                '                latitude double precision, \n'
                '                date timestamp, \n'
                '                year int, \n'
                '                month int, \n'
                '                day int, \n'
                '                time time\n'
                '                );\n'
                '    ',
 'RedshiftPid': 1073741949,
 'RedshiftQueryId': 0,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1197',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sun, 16 Jun 2024 18:23:31 GMT',
                                      'x-amzn-requestid': '38595100-eacc-4bd8-a660-af23419ebd3e'},
                      'HTTPStatusCode': 200,
                      'RequestId': '38595100-eacc-4bd8-a660-af23419ebd3e',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2024, 6, 16, 18, 23, 23, 302000, tzinfo=tzlocal()),
 'WorkgroupName': 'redshift-velib'}
[2024-06-16T18:23:32.233+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=s3_to_ml_to_postgres, task_id=setup_create_table, execution_date=20240616T182138, start_date=20240616T182320, end_date=20240616T182332
[2024-06-16T18:23:32.240+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 133 for task setup_create_table (Statement '89441591-f85c-49c0-81e2-7f3779506201' terminated with status FAILED. Response details: {'CreatedAt': datetime.datetime(2024, 6, 16, 18, 23, 21, 605000, tzinfo=tzlocal()),
 'Database': 'dev',
 'DbUser': 'IAM:kevin_project',
 'Duration': -1,
 'Error': 'ERROR: permission denied for relation transformed_data',
 'HasResultSet': False,
 'Id': '89441591-f85c-49c0-81e2-7f3779506201',
 'QueryString': '\n'
                'DROP TABLE IF EXISTS transformed_data;\n'
                'CREATE TABLE transformed_data(\n'
                '                stationcode bigint,\n'
                '                name varchar(255),\n'
                '                is_installed boolean,\n'
                '                capacity int,\n'
                '                numdocksavailable int,\n'
                '                numbikesavailable int,\n'
                '                mechanical int,\n'
                '                ebike int,\n'
                '                is_renting boolean,\n'
                '                is_returning boolean,\n'
                '                nom_arrondissement_communes varchar(255),\n'
                '                code_insee_commune varchar(255),\n'
                '                longitude double precision, \n'
                '                latitude double precision, \n'
                '                date timestamp, \n'
                '                year int, \n'
                '                month int, \n'
                '                day int, \n'
                '                time time\n'
                '                );\n'
                '    ',
 'RedshiftPid': 1073741949,
 'RedshiftQueryId': 0,
 'ResponseMetadata': {'HTTPHeaders': {'content-length': '1197',
                                      'content-type': 'application/x-amz-json-1.1',
                                      'date': 'Sun, 16 Jun 2024 18:23:31 GMT',
                                      'x-amzn-requestid': '38595100-eacc-4bd8-a660-af23419ebd3e'},
                      'HTTPStatusCode': 200,
                      'RequestId': '38595100-eacc-4bd8-a660-af23419ebd3e',
                      'RetryAttempts': 0},
 'ResultRows': -1,
 'ResultSize': -1,
 'Status': 'FAILED',
 'UpdatedAt': datetime.datetime(2024, 6, 16, 18, 23, 23, 302000, tzinfo=tzlocal()),
 'WorkgroupName': 'redshift-velib'}; 30860)
[2024-06-16T18:23:32.261+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-06-16T18:23:32.270+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
